main : EncryptoMania.cpp CeaserCipher.cpp
	g++ -o asciiArt.o -c asciiArt.cpp
	g++ -o EncryptoMania.o -c EncryptoMania.cpp
	g++ -o CeaserCipher.o -c CeaserCipher.cpp
	g++ -o EncryptoMania EncryptoMania.o CeaserCipher.o asciiArt.o